# Server Configuration
server:
  port: 8989
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: '@deboo@coop'
    key-alias: deboo-app

# name of application
spring:
  application:
    name: BOT-GAME

  # configuration for connecting to the PostgreSQL database
  datasource:
    url: jdbc:postgresql://localhost:5432/bot_game
    username: postgres
    password: 1313

  # Set the configuration for Hibernate, the ORM framework used by Spring Data JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
    hibernate:
      ddl-auto: update  # Set the strategy for Hibernate to create/create-drop/update the database schema.

  # Set the configuration for handling multipart file uploads
  servlet:
    multipart:
      max-file-size: 10MB # Maximum size of each file in a multipart request
      max-request-size: 10MB # Maximum size of the entire multipart request


# Set the conditional property for seeding the database
# NOTE: Set it to true only if you are starting this app for the first time.
database:
  seed: false

# Secret key for jwt
SECRET_KEY: "AB(G+KbPeShVkYp3s6v9y$B&E)H@McQf"
